name: test

on:
  push:
    branches:
      - test

jobs:
  build-windows:
    name: build-windows
    runs-on: windows-latest
    steps:
      - name: checkout code
        uses: actions/checkout@v4
      - name: setup go
        uses: actions/setup-go@v5
        with:
          go-version: '>=1.22.0'
      - name: build libwg
        run: cd libwg && ./build.ps1
      - name: rust install gnu toolchain
        run: rustup toolchain install stable-gnu
      - name: rust use gnu toolchain
        run: rustup default stable-x86_64-pc-windows-gnu
      - name: build package
        run: cargo build --release
      - name: build check result
        run: |
          Move-Item -Path "target/release/corplink-rs.exe" -Destination "."
          Move-Item -Path "config/config.json" -Destination "."
          Compress-Archive -Path corplink-rs.exe,config.json -Destination corplink-rs-${{ github.ref_name }}-windows.zip
